name: Deploy to Staging

on:
  push:
    branches: [dev] # Workflow jalan saat push ke branch 'dev'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Server Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/evently-server:staging ./server
          docker push ${{ secrets.DOCKER_USERNAME }}/evently-server:staging

      - name: Build and Push Client Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/evently-client:staging ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/evently-client:staging

      - name: Deploy to EC2 (Staging)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_STAGING_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker run -d --name evently-server -p 5000:5000 -e PORT=${{ secrets.PORT }} -e HOSTNAME=${{ secrets.HOSTNAME }} -e MONGO_URL=${{ secrets.MONGO_URL }} -e CLIENT_URL=${{ secrets.CLIENT_URL }} -e NODEMAILER_HOST=${{ secrets.NODEMAILER_HOST }} -e NODEMAILER_PORT=${{ secrets.NODEMAILER_PORT }} -e NODEMAILER_UNAME=${{ secrets.NODEMAILER_UNAME }} -e NODEMAILER_PASS=${{ secrets.NODEMAILER_PASS }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e GOOGLE_CLIENTID=${{ secrets.GOOGLE_CLIENTID }} -e GOOGLE_CLIENTSECRET=${{ secrets.GOOGLE_CLIENTSECRET }} -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} --health-cmd="curl -f http://localhost:5000/api/health || exit 1" --health-interval=30s --health-timeout=5s --health-retries=3 ${{ secrets.DOCKER_USERNAME }}/evently-server:staging
