name: 🚀 Deploy Evently to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🔐 Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy app on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'

            echo "📁 Navigating to deploy directory..."
            mkdir -p ~/evently-deploy
            cd ~/evently-deploy

            echo "📄 Writing .env file..."
            cat <<EOT > .env
            JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            MONGO_URL=${{ secrets.MONGO_URL }}
            CLIENT_URL=${{ secrets.CLIENT_URL }}
            NODEMAILER_HOST=${{ secrets.NODEMAILER_HOST }}
            NODEMAILER_PORT=${{ secrets.NODEMAILER_PORT }}
            NODEMAILER_UNAME=${{ secrets.NODEMAILER_UNAME }}
            NODEMAILER_PASS=${{ secrets.NODEMAILER_PASS }}
            EOT

            echo "🐳 Pulling latest server image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/evently-server:staging

            echo "🧹 Removing old server container if exists..."
            docker rm -f evently-server || true

            echo "🚀 Running new server container..."
            docker run -d \
              --name evently-server \
              --env-file .env \
              -p 5000:5000 \
              --health-cmd="curl -f http://localhost:5000/api/health || exit 1" \
              --health-interval=30s \
              --health-timeout=5s \
              --health-retries=3 \
              ${{ secrets.DOCKER_USERNAME }}/evently-server:staging

            echo "🐳 Pulling latest client image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/evently-client:staging

            echo "🧹 Removing old client container if exists..."
            docker rm -f evently-client || true

            echo "🚀 Running new client container..."
            docker run -d \
              --name evently-client \
              -p 80:5173 \
              ${{ secrets.DOCKER_USERNAME }}/evently-client:staging

            echo "✅ Deployment finished!"

          EOF
